services:
  mongo:
    image: mongo:7
    container_name: taskboard-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: taskboard-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: taskboard-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: taskboard-api
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - redis
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    container_name: taskboard-worker
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
      - rabbitmq

volumes:
  mongo_data:
